name: deploy to gh pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev-branch" branch
  push:
    branches: ["dev-branch"]
  pull_request:
    branches: ["dev-branch"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: setup and runs tw
        run: |
          npm install -D tailwindcss
          npx tailwindcss -i ./wwwroot/css/app.css -o ./wwwroot/css/app.min.css --minify

      - name: Add .nojekyll file
        run: touch ./wwwroot/.nojekyll

      - name: Change base-tag in all html files
        run: sed -i 's/<base href="\/wwwroot\/"[[:blank:]]*\/>/<base href="\/bst-tw-design\/" \/>/g' $(find . -type f -name '*.html')

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./wwwroot